2021-09-29 12:36:52,358 INFO: Microblog startup [in D:\PlayGround\microblog\app\__init__.py:48]
2021-09-29 12:36:58,145 ERROR: Exception on /edit_profile [GET] [in d:\playground\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\playground\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\playground\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\playground\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\playground\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\playground\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\playground\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\playground\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\PlayGround\microblog\app\routes.py", line 85, in edit_profile
    form = EditProfileForm(curret_user.username)
NameError: name 'curret_user' is not defined
